HostKey /etc/ssh/persistent-host-keys/ssh_host_ed25519_key
HostKey /etc/ssh/persistent-host-keys/ssh_host_rsa_key

PermitRootLogin prohibit-password
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
AuthenticationMethods publickey
PermitEmptyPasswords no

AllowAgentForwarding no
AllowTcpForwarding yes
GatewayPorts no
X11Forwarding no
PermitTunnel no
PermitUserEnvironment no

ClientAliveInterval 60
ClientAliveCountMax 3
LoginGraceTime 30
MaxAuthTries 3
